### PR TITLE
interp: fix range expression handling

### LINKED ISSUE #340: for loop edge case freezes yaegi
The following program `sample.go` triggers a panic:

```go
package main

import "fmt"

func main() {
        v := []int{1, 2, 3}
        for i := range v {
                v = append(v, i)
        }
        fmt.Println(v)
}
}
```

Expected result:
```console
$ go run ./sample.go
// ouput
[1 2 3 0 1 2]
```

Got:
```console
$ yaegi ./sample.go
// ouput
```
There is no output, it seems to get stuck

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

Updates #340.

### CODE REVIEW

File: interp/run.go [hunk 1]
```diff
@@ -1538,16 +1538,16 @@ func _range(n *node) {
 	tnext := getExec(n.tnext)
 
 	var value func(*frame) reflect.Value
+	var a reflect.Value
```
Comment (mvertes) [inline interp/run.go]: No. You are using this variable to store live data computed during interpretation (the actual array). It has to be stored in the frame. The frame position and type has to be allocated during CFG.

The flaw in my implementation of range is that only 1 register is used to store the range index (store at index0 location in frame). We should use a second register to store the range limit (an integer), computed once during the init sequence. Then the test before index increment should be done against this limit value instead of array length (which can change). No need for genValueRangeArray. But need to allocate a second register for storing range limit ans remember its location in say index1. The allocation has to be done with a `sc.Add(limitType)`  (where limit type is an `int`) around  https://github.com/containous/yaegi/blob/2c2b471cb91f520b10f9ea8e0f988de221c94b6a/interp/cfg.go#L106

File: interp/run.go [hunk 2]
```diff
@@ -1538,16 +1538,16 @@ func _range(n *node) {
...
 	if len(n.child) == 4 {
 		an := n.child[2]
 		index1 := n.child[1].findex // array value location in frame
 		if isString(an.typ.TypeOf()) {
 			value = genValueAs(an, rat) // range on string iterates over runes
 		} else {
-			value = genValueArray(an)
```
Comment (mvertes) [inline interp/run.go]: no change here, see above explanation

File: interp/run.go [hunk 3]
```diff
@@ -1562,10 +1562,9 @@ func _range(n *node) {
...
```
Comment (mvertes) [inline interp/run.go]: no change here as well, see above

File: interp/run.go (hunk 1 above)
Comment (kortschak) [reply interp/run.go]: I don't think so. A range on an array results in a copy of the array. If you don't do this you will not execute the same way as the Go spec and you will fail the range1.go test.

File: interp/run.go [hunk 4]
```diff
@@ -1578,6 +1577,7 @@ func _range(n *node) {
 	// Init sequence
 	next := n.exec
 	n.child[0].exec = func(f *frame) bltn {
+		a = value(f)
```
Comment (mvertes) [inline interp/run.go]: we should have a frame location (say index1) to store the array length:

```go
v1 := f.data[index1]
v1.SetInt(value(f).Len())
```

File: interp/value.go [hunk 5]
```diff
@@ -118,6 +118,22 @@ func genValueArray(n *node) func(*frame) reflect.Value {
 	return value
 }
 
+func genValueRangeArray(n *node) func(*frame) reflect.Value {
```
Comment (mvertes) [inline interp/value.go]: no need for this function

Comment (kortschak) [reply interp/value.go]: See previous comment.

File: interp/run.go (hunk 1 above)
Comment (mvertes) [reply interp/run.go]: Right, `range1.go` demonstrates that, although I could not find a clear mention in the spec. I agree with your implementation using `genValueArray` except its value has to be stored in the frame.

File: interp/run.go (hunk 4 above)
Comment (kortschak) [reply interp/run.go]: As pointed out, this will still fail to match the compiled code's behaviour. Making a new value that is outside the scope of the interpreted code is far more aligned with the compiled code case where the range expression is not available to the Go program using anything except unsafe access.

In both the slice and array cases the value of the range expression is copied (it is dangerous to think of arrays and slices as arrays since this leads to misconceptions of shared behaviours). In the case of a slice, we have approximately what you are suggesting while in the array case you get an entire copy of the array. Now you could differentiate and copy for the array and keep the length for the slice, but we already get that behaviour with the change here.

File: interp/run.go (hunk 1 above)
Comment (kortschak) [reply interp/run.go]: I don't understand why it needs to be in the frame. In the gc, there is no programmatic access to the value of the range expression after it has been evaluated. As far as the user code is concerned the value is a magic thing that exists in the æther. That is replicated here.

Comment (mvertes) [reply interp/run.go]: If the loop is running in goroutines, the same memory location to store the array will be used by concurrent tasks (as the _range generator is run only once per code chunk), as opposed to a local stack in compiled go. Using the frame ensures the same behaviour as in compiled go.

Comment (mvertes) [reply interp/run.go]: As the frame is the works a local stack within the interpreter

Comment (kortschak) [reply interp/run.go]: OK. This makes sense. I'll give it a go. How do I make a slot in the frame, it's not immediately obvious to me how to do this.

This is what I have tried. It fails.

```diff
diff --git a/interp/cfg.go b/interp/cfg.go
index be1e43e..8b6665d 100644
--- a/interp/cfg.go
+++ b/interp/cfg.go
@@ -98,7 +98,13 @@ func (interp *Interpreter) cfg(root *node) ([]*node, error) {
                                        case stringT:
                                                ktyp = sc.getType("int")
                                                vtyp = sc.getType("rune")
-                                       case arrayT, variadicT:
+                                       case arrayT:
+                                               otyp := o.typ
+                                               oindex := sc.add(otyp)
+                                               sc.sym[o.ident] = &symbol{index: oindex, kind: varSym, typ: otyp}
+                                               o.findex = oindex
+                                               fallthrough
+                                       case variadicT:
                                                ktyp = sc.getType("int")
                                                vtyp = o.typ.val
                                        }
diff --git a/interp/run.go b/interp/run.go
index f04ae9a..b7e7295 100644
--- a/interp/run.go
+++ b/interp/run.go
@@ -1534,11 +1534,11 @@ var rat = reflect.ValueOf((*[]rune)(nil)).Type().Elem() // runes array type
 
 func _range(n *node) {
        index0 := n.child[0].findex // array index location in frame
+       index1 := n.child[1].findex // range expression
        fnext := getExec(n.fnext)
        tnext := getExec(n.tnext)
 
        var value func(*frame) reflect.Value
-       var a reflect.Value
        if len(n.child) == 4 {
                an := n.child[2]
                index1 := n.child[1].findex // array value location in frame
@@ -1549,6 +1549,7 @@ func _range(n *node) {
                }
                n.exec = func(f *frame) bltn {
                        v0 := f.data[index0]
+                       a := f.data[index1]
                        v0.SetInt(v0.Int() + 1)
                        i := int(v0.Int())
                        if i >= a.Len() {
@@ -1566,6 +1567,7 @@ func _range(n *node) {
                }
                n.exec = func(f *frame) bltn {
                        v0 := f.data[index0]
+                       a := f.data[index1]
                        v0.SetInt(v0.Int() + 1)
                        if int(v0.Int()) >= a.Len() {
                                return fnext
@@ -1577,8 +1579,8 @@ func _range(n *node) {
        // Init sequence
        next := n.exec
        n.child[0].exec = func(f *frame) bltn {
-               a = value(f)
                f.data[index0].SetInt(-1)
+               f.data[index1].Set(value(f))
                return next
        }
 }
```

File: interp/run.go (hunk 4 above)
Comment (mvertes) [reply interp/run.go]: Agree. No need to store just the index as we have to get access to the entire array copy anyway

**Comment by mvertes** [comment]
We can now merge this PR. I found other checks to do in CFG about range statement, but they can be added later, and should not affect the logic in _range.

**Comment by kortschak** [comment]
Thanks. I can use your addition to figure out how to add the similar requirements for in-frame storage of of the iterator state for the map range fix PR #393.
