### PR TITLE
fix: range over channels returned by binary calls

### LINKED ISSUE #690: Can't range over `time.Tick`
The following program `sample.go` triggers a panic:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	bar := time.Second
	for _ = range time.Tick(bar) {
		fmt.Println("success")
		return
	}

}
```

Expected result:
```console
$ go run ./sample.go
success
```

Got:
```console
$ yaegi ./sample.go
scope.go:157: nil type
nil type
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc00031c000, 0x40)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc0000b7df0)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:330 +0xbc
panic(0xc9b420, 0xc000204660)
	/usr/lib/go/src/runtime/panic.go:969 +0x166
log.Panic(0xc0000b73a8, 0x1, 0x1)
	/usr/lib/go/src/log/log.go:351 +0xac
github.com/containous/yaegi/interp.(*scope).add(0xc0002f95e0, 0x0, 0x1)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/scope.go:157 +0x1bf
github.com/containous/yaegi/interp.(*Interpreter).cfg.func1(0xc000215b00, 0xc0000b7c98)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/cfg.go:130 +0x1a8b
github.com/containous/yaegi/interp.(*node).Walk(0xc000215b00, 0xc0000b7c98, 0xc0000b7c68)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:188 +0xc9
github.com/containous/yaegi/interp.(*node).Walk(0xc000215400, 0xc0000b7c98, 0xc0000b7c68)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:192 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000215300, 0xc0000b7c98, 0xc0000b7c68)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:192 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000214d00, 0xc0000b7c98, 0xc0000b7c68)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:192 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000214800, 0xc0000b7c98, 0xc0000b7c68)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:192 +0x70
github.com/containous/yaegi/interp.(*node).Walk(0xc000214100, 0xc0000b7c98, 0xc0000b7c68)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:192 +0x70
github.com/containous/yaegi/interp.(*Interpreter).cfg(0xc00022e1a0, 0xc000214100, 0x7ffde6ef71aa, 0xe, 0xc00021a088, 0x4, 0x7ffde6ef71aa, 0xe, 0x0)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/cfg.go:55 +0x160
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc00022e1a0, 0xc000302000, 0x93, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jlevesy/code/src/github.com/containous/yaegi/interp/interp.go:357 +0x28d
main.main()
	/home/jlevesy/code/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:143 +0x553
```

### PR DESCRIPTION
**Pull request by jlevesy**
This PR allows to range over channels returned by binary calls. 

Fixes #690

### CODE REVIEW

File: interp/scope.go [hunk 1]
```diff
@@ -135,9 +135,25 @@ func (s *scope) rangeChanType(n *node) *itype {
 			return t
 		}
 	}
-	if c := n.child[1]; c.typ != nil && c.typ.cat == chanT {
+
+	c := n.child[1]
+	if c.typ != nil && c.typ.cat == chanT {
 		return c.typ
 	}
+	if isBinCall(c) &&
```
Comment (nrwiersma) [inline interp/scope.go:143]: It would be better here to check for `c.typ.cat` of `valueT` and a `c.typ.rtype.Kind()` of `reflect.Chan`. Also you will need to hoist the `c.typ == nil`.

File: interp/scope.go [hunk 2]
```diff
@@ -135,9 +135,25 @@ func (s *scope) rangeChanType(n *node) *itype {
...
+		c.child[0].typ.rtype.NumOut() > 0 &&
+		c.child[0].typ.rtype.Out(0).Kind() == reflect.Chan {
+		o := c.child[0].typ.rtype.Out(0)
+		return &itype{
+			cat:   chanT,
+			rtype: o,
```
Comment (nrwiersma) [inline interp/scope.go:149]: This isnt needed.

File: interp/scope.go (hunk 1 above)
Comment (jlevesy) [reply interp/scope.go:143]: Will do, thanks.

Comment (jlevesy) [reply interp/scope.go]: (although I'm not super clear about how my previous code was actually working :sweat_smile: )

**Comment by jlevesy** [comment]
Thanks, I will see what I can do !

**Comment by jlevesy** [comment]
Follow up created https://github.com/containous/yaegi/issues/701
