### PR TITLE
fix: correct range on arrays of interface objects

### LINKED ISSUE #784: reflect.Set: value of type interface {} is not assignable to type interp.valueInterface
yaegi version: 0.8.13

The following program `sample.go` triggers a panic:

```go
package main

import "fmt"

// Filter is a filter interface
type Filter interface {
	Bounds(srcBounds string) (dstBounds string)
}

// GIFT type
type GIFT struct {
	Filters []Filter
}

// New creates a new filter list and initializes it with the given slice of filters.
func New(filters ...Filter) *GIFT {
	return &GIFT{
		Filters: filters,
	}
}

// Bounds calculates the appropriate bounds for the result image after applying all the added filters.
func (g *GIFT) Bounds(srcBounds string) (dstBounds string) {
	dstBounds = srcBounds
	for _, f := range g.Filters {
		dstBounds = f.Bounds(dstBounds)
	}
	return dstBounds
}

type resizeFilter struct{}

func (p *resizeFilter) Bounds(srcBounds string) (dstBounds string) {
	return srcBounds
}

func main() {
	var filters []Filter
	bounds := "foo"
	g := New(filters...)
	fmt.Println(g.Bounds(bounds))
}
```

Expected result:
```console
$ go run ./sample.go
foo
```

Got:
```console
$ yaegi ./sample.go
./sample.go:24:2: panic
./sample.go:38:6: panic
reflect.Set: value of type interface {} is not assignable to type interp.valueInterface
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc000382800, 0x40)
        /usr/lib/go-1.14/src/runtime/debug/stack.go:24 +0x9d
github.com/containous/yaegi/interp.(*Interpreter).Eval.func1(0xc0002a9dd8)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/interp.go:333 +0xbc
panic(0xd2ed00, 0xc0000ab3e0)
        /usr/lib/go-1.14/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/interp.runCfg.func1(0xc0004300a0, 0xc000445800)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/run.go:119 +0x20c
panic(0xd2ed00, 0xc0000ab3e0)
        /usr/lib/go-1.14/src/runtime/panic.go:969 +0x166
github.com/containous/yaegi/interp.runCfg.func1(0xc000430280, 0xc000442400)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/run.go:119 +0x20c
panic(0xd2ed00, 0xc0000ab3e0)
        /usr/lib/go-1.14/src/runtime/panic.go:969 +0x166
reflect.Value.assignTo(0xd5f100, 0xc0000ab3b0, 0x194, 0xe6b731, 0xb, 0xdb6180, 0x0, 0xc0000ab3c0, 0xe6b731, 0x17)
        /usr/lib/go-1.14/src/reflect/value.go:2403 +0x426
reflect.Value.Set(0xdb6180, 0xc0000afa20, 0x199, 0xd5f100, 0xc0000ab3b0, 0x194)
        /usr/lib/go-1.14/src/reflect/value.go:1532 +0xbd
github.com/containous/yaegi/interp._range.func1(0xc000430280, 0xc0003b5140)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/run.go:2177 +0x1cd
github.com/containous/yaegi/interp.runCfg(0xc000442400, 0xc000430280)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/run.go:125 +0x6d
github.com/containous/yaegi/interp.call.func7(0xc0004300a0, 0xc00045a070)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/run.go:1023 +0xc42
github.com/containous/yaegi/interp.runCfg(0xc000445800, 0xc0004300a0)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/run.go:125 +0x6d
github.com/containous/yaegi/interp.(*Interpreter).run(0xc0000cc1a0, 0xc000445000, 0xc000430000)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/run.go:103 +0x247
github.com/containous/yaegi/interp.(*Interpreter).Eval(0xc0000cc1a0, 0xc00043a000, 0x351, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/me/src/softwares/go/src/github.com/containous/yaegi/interp/interp.go:416 +0x5f7
main.main()
        /home/me/src/softwares/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:166 +0x6e2
```

### PR DESCRIPTION
**Pull request by mvertes**
Fixes #784.

### CODE REVIEW

File: _test/issue-784.go [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+		dstBounds = f.Bounds(dstBounds)
+	}
+	return dstBounds
+}
+
+type resizeFilter struct{}
+
+func (p *resizeFilter) Bounds(srcBounds string) (dstBounds string) {
+	return srcBounds
+}
```
Comment (mpl) [inline _test/issue-784.go:35]: this part is not needed. Simpler tests are easier to maintain.

Comment (mvertes) [reply _test/issue-784.go]: done

**Comment by Trois-Six** [comment]
Hello,
I think that this breaks something in Traefik with Pilot:

```
$ go get github.com/containous/yaegi@9c51f6bb694888db4cebc2886680d41b98552105
go: github.com/containous/yaegi 9c51f6bb694888db4cebc2886680d41b98552105 => v0.8.14-0.20200723102504-9c51f6bb6948
go: downloading github.com/containous/yaegi v0.8.14-0.20200723102504-9c51f6bb6948
$ go build ./cmd/traefik
$ go run ./cmd/traefik/ --log.level=DEBUG --api.insecure --entrypoints.web.address=:8180   --experimental.pilot.token=xxx --experimental.plugins.cache.moduleName=github.com/containous/plugin-simplecache --experimental.plugins.cache.version=v0.1.1
INFO[0000] Configuration loaded from file: /home/me/src/softwares/go/src/github.com/containous/traefik/traefik.toml 
INFO[2020-07-23T13:03:02+02:00] Traefik version dev built on I don't remember exactly 
DEBU[2020-07-23T13:03:02+02:00] Static configuration loaded {"global":{"checkNewVersion":true},"serversTransport":{"maxIdleConnsPerHost":200},"entryPoints":{"traefik":{"address":":8080","transport":{"lifeCycle":{"graceTimeOut":10000000000},"respondingTimeouts":{"idleTimeout":180000000000}},"forwardedHeaders":{},"http":{}},"web":{"address":":10080","transport":{"lifeCycle":{"graceTimeOut":10000000000},"respondingTimeouts":{"idleTimeout":180000000000}},"forwardedHeaders":{},"http":{}}},"providers":{"providersThrottleDuration":2000000000,"file":{"watch":true,"filename":"../dynamic_conf.toml"}},"api":{"insecure":true,"dashboard":true},"log":{"level":"DEBUG","format":"common"},"accessLog":{"format":"common","filters":{},"fields":{"defaultMode":"keep","headers":{"defaultMode":"drop"}}},"experimental":{"pilot":{"token":"xxx"},"plugins":{"cache":{"moduleName":"github.com/containous/plugin-simplecache","version":"v0.1.1"}}}} 
INFO[2020-07-23T13:03:02+02:00] 
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://docs.traefik.io/contributing/data-collection/ 
DEBU[2020-07-23T13:03:02+02:00] loading of plugin: cache: github.com/containous/plugin-simplecache@v0.1.1 
2020/07/23 13:03:05 traefik.go:75: command traefik error: github.com/containous/plugin-simplecache: failed to import plugin code "github.com/containous/plugin-simplecache": runtime error: invalid memory address or nil pointer dereference
exit status 1
$
$
$ go get github.com/containous/yaegi@v0.8.13
$ go build ./cmd/traefik
$ go run ./cmd/traefik/ --log.level=DEBUG --api.insecure --entrypoints.web.address=:8180   --experimental.pilot.token=xxx --experimental.plugins.cache.moduleName=github.com/containous/plugin-simplecache --experimental.plugins.cache.version=v0.1.1
INFO[0000] Configuration loaded from file: /home/me/src/softwares/go/src/github.com/containous/traefik/traefik.toml 
INFO[2020-07-23T13:41:49+02:00] Traefik version dev built on I don't remember exactly 
DEBU[2020-07-23T13:41:49+02:00] Static configuration loaded {"global":{"checkNewVersion":true},"serversTransport":{"maxIdleConnsPerHost":200},"entryPoints":{"traefik":{"address":":8080","transport":{"lifeCycle":{"graceTimeOut":10000000000},"respondingTimeouts":{"idleTimeout":180000000000}},"forwardedHeaders":{},"http":{}},"web":{"address":":10080","transport":{"lifeCycle":{"graceTimeOut":10000000000},"respondingTimeouts":{"idleTimeout":180000000000}},"forwardedHeaders":{},"http":{}}},"providers":{"providersThrottleDuration":2000000000,"file":{"watch":true,"filename":"../dynamic_conf.toml"}},"api":{"insecure":true,"dashboard":true},"log":{"level":"DEBUG","format":"common"},"accessLog":{"format":"common","filters":{},"fields":{"defaultMode":"keep","headers":{"defaultMode":"drop"}}},"experimental":{"pilot":{"token":"xxx"},"plugins":{"cache":{"moduleName":"github.com/containous/plugin-simplecache","version":"v0.1.1"}}}} 
INFO[2020-07-23T13:41:49+02:00] 
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://docs.traefik.io/contributing/data-collection/ 
DEBU[2020-07-23T13:41:49+02:00] loading of plugin: cache: github.com/containous/plugin-simplecache@v0.1.1 
INFO[2020-07-23T13:41:53+02:00] Starting provider aggregator.ProviderAggregator {} 
DEBU[2020-07-23T13:41:53+02:00] Start TCP Server                              entryPointName=web
DEBU[2020-07-23T13:41:53+02:00] Start TCP Server                              entryPointName=traefik
INFO[2020-07-23T13:41:53+02:00] Starting provider *file.Provider {"watch":true,"filename":"../dynamic_conf.toml"} 
ERRO[2020-07-23T13:41:53+02:00] Cannot start the provider *file.Provider: field not found, node: plugins 
INFO[2020-07-23T13:41:53+02:00] Starting provider *traefik.Provider {}       
DEBU[2020-07-23T13:41:53+02:00] Configuration received from provider internal: {"http":{"routers":{"api":{"entryPoints":["traefik"],"service":"api@internal","rule":"PathPrefix(`/api`)","priority":2147483646},"dashboard":{"entryPoints":["traefik"],"middlewares":["dashboard_redirect@internal","dashboard_stripprefix@internal"],"service":"dashboard@internal","rule":"PathPrefix(`/`)","priority":2147483645}},"services":{"api":{},"dashboard":{},"noop":{}},"middlewares":{"dashboard_redirect":{"redirectRegex":{"regex":"^(http:\\/\\/(\\[[\\w:.]+\\]|[\\w\\._-]+)(:\\d+)?)\\/$","replacement":"${1}/dashboard/","permanent":true}},"dashboard_stripprefix":{"stripPrefix":{"prefixes":["/dashboard/","/dashboard"]}}}},"tcp":{},"tls":{}}  providerName=internal
DEBU[2020-07-23T13:41:53+02:00] Added outgoing tracing middleware api@internal  middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=api@internal
DEBU[2020-07-23T13:41:53+02:00] Added outgoing tracing middleware dashboard@internal  middlewareName=tracing middlewareType=TracingForwarder entryPointName=traefik routerName=dashboard@internal
DEBU[2020-07-23T13:41:53+02:00] Creating middleware                           entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_stripprefix@internal middlewareType=StripPrefix
DEBU[2020-07-23T13:41:53+02:00] Adding tracing to middleware                  entryPointName=traefik middlewareName=dashboard_stripprefix@internal routerName=dashboard@internal
DEBU[2020-07-23T13:41:53+02:00] Creating middleware                           entryPointName=traefik routerName=dashboard@internal middlewareType=RedirectRegex middlewareName=dashboard_redirect@internal
DEBU[2020-07-23T13:41:53+02:00] Setting up redirection from ^(http:\/\/(\[[\w:.]+\]|[\w\._-]+)(:\d+)?)\/$ to ${1}/dashboard/  middlewareName=dashboard_redirect@internal entryPointName=traefik routerName=dashboard@internal middlewareType=RedirectRegex
DEBU[2020-07-23T13:41:53+02:00] Adding tracing to middleware                  entryPointName=traefik routerName=dashboard@internal middlewareName=dashboard_redirect@internal
DEBU[2020-07-23T13:41:53+02:00] Creating middleware                           entryPointName=traefik middlewareName=traefik-internal-recovery middlewareType=Recovery
DEBU[2020-07-23T13:41:53+02:00] No default certificate, generating one       
^CINFO[2020-07-23T13:42:01+02:00] I have to go...                              
INFO[2020-07-23T13:42:01+02:00] Stopping server gracefully                   
DEBU[2020-07-23T13:42:01+02:00] Waiting 10s seconds before killing connections.  entryPointName=traefik
DEBU[2020-07-23T13:42:01+02:00] Waiting 10s seconds before killing connections.  entryPointName=web
ERRO[2020-07-23T13:42:01+02:00] accept tcp [::]:8080: use of closed network connection  entryPointName=traefik
ERRO[2020-07-23T13:42:01+02:00] accept tcp [::]:10080: use of closed network connection  entryPointName=web
ERRO[2020-07-23T13:42:01+02:00] close tcp [::]:8080: use of closed network connection  entryPointName=traefik
DEBU[2020-07-23T13:42:01+02:00] Entry point traefik closed                    entryPointName=traefik
ERRO[2020-07-23T13:42:01+02:00] close tcp [::]:10080: use of closed network connection  entryPointName=web
DEBU[2020-07-23T13:42:01+02:00] Entry point web closed                        entryPointName=web
INFO[2020-07-23T13:42:01+02:00] Server stopped                               
INFO[2020-07-23T13:42:01+02:00] Shutting down     
```
