### PR TITLE
fix: handle printf changing nil type

### LINKED ISSUE #659: nil from recover function could not be compared properly
The following program `sample.go` has an unexpected result:

```go
package main

import "fmt"

func div(a, b int) (result int) {
	defer func() {
		r := recover()

		fmt.Printf("r = %#v\n", r)

		if r != nil {
			result = 0
		}
	}()

	return a / b
}

func main() {
	println(div(30, 2))

}

```

Expected result:
```console
$ yaegi ./sample.go

r = <nil>
15
```

Got:
```console
$ yaegi ./sample.go
r = <nil>
0
```

So the nil value r in the defer function is not real "nil" value?

### PR DESCRIPTION
**Pull request by nrwiersma**
When running a function on `r` it was modifying the value, making `isNil` and `isNotNil` no longer match properly.

Fixes #659

### CODE REVIEW

File: _test/recover3.go [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+	}
+	if r != nil {
+		println("exception")
+	}
+}
+
+// Output:
+// hello
+// <nil>
+// world
```
Comment (mvertes) [inline _test/recover3.go:22]: Better to have a `<newline>` char at the end of files

File: _test/recover4.go [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+	return a / b
+}
+
+func main() {
+	println(div(30, 2))
+}
+
+// Output:
+// r = <nil>
+// 15
```
Comment (mvertes) [inline _test/recover4.go:25]: Please add a `<newline>` here too.
