### PR TITLE
fix: compute numeral constant on typed objects

### LINKED ISSUE #631: Defining typed constant numbers
The following program `sample.go` triggers an unexpected error:

```go
package main

type Kind int

const (
    None Kind = 0
    Left Kind = 1 << iota
    Right
    Both Kind = Left | Right
)

func main() {
    println(None, Left, Right, Both)
}
```

Expected result:
```console
$ go run ./sample.go
0 2 4 6
```

Got:
```console
$ yaegi ./sample.go
sample.go:7:2: constant definition loop
```

### PR DESCRIPTION
**Pull request by mvertes**
Remove the spurious constraint that a constant must be untyped
when testing for arithmetic properties.

Fixes #631.

### CODE REVIEW

File: _test/const12.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package main
```
Comment (mpl) [inline _test/const12.go:1]: I think that instead of this test, we should rather add a simple unit test for isNatural that checks that it returns true for a typed const as well. I can try to do it if you want?

**Comment by mvertes** [comment]
I agree with your suggestion to apply this PR (with additional test on `isNatural`), and keep #631 open for now.
