### PR TITLE
fix: add mutual exclusion locks for cancelable select

### LINKED ISSUE #815: race condition detected when canceling select
This issue is not deterministic, but has occured a few times with travis CI, or when running the following (with count > 100):

```console
GO111MODULE=off go test -race -count=1000 -timeout=0 ./cmd/yaegi
```

which can produce:

```
=== RUN   TestYaegiCmdCancel
    yaegi_test.go:101: race detected running yaegi command canceling "select {}\n": exit status 66
    yaegi_test.go:103: ==================
        WARNING: DATA RACE
        Write at 0x00c000334068 by goroutine 14:
          github.com/containous/yaegi/interp.(*Interpreter).run()
              /home/marc/go/src/github.com/containous/yaegi/interp/run.go:97 +0x386
          github.com/containous/yaegi/interp.(*Interpreter).Eval()
              /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:408 +0x5bb
          github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext.func1()
              /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:447 +0xa4
        
        Previous read at 0x00c000334068 by goroutine 12:
          github.com/containous/yaegi/interp._select.func2()
              /home/marc/go/src/github.com/containous/yaegi/interp/run.go:2972 +0x9c
          github.com/containous/yaegi/interp.runCfg()
              /home/marc/go/src/github.com/containous/yaegi/interp/run.go:125 +0xb4
          github.com/containous/yaegi/interp.(*Interpreter).run()
              /home/marc/go/src/github.com/containous/yaegi/interp/run.go:103 +0x58a
          github.com/containous/yaegi/interp.(*Interpreter).Eval()
              /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:408 +0x5bb
          github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext.func1()
              /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:447 +0xa4
        
        Goroutine 14 (running) created at:
          github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext()
              /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:445 +0x237
          github.com/containous/yaegi/interp.(*Interpreter).REPL()
              /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:553 +0x8a5
          main.run()
              /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/run.go:64 +0x852
          main.main()
              /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:128 +0x37f
        
        Goroutine 12 (running) created at:
          github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext()
              /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:445 +0x237
          github.com/containous/yaegi/interp.(*Interpreter).REPL()
              /home/marc/go/src/github.com/containous/yaegi/interp/interp.go:553 +0x8a5
          main.run()
              /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/run.go:64 +0x852
          main.main()
              /home/marc/go/src/github.com/containous/yaegi/cmd/yaegi/yaegi.go:128 +0x37f
        ==================
        Found 1 data race(s)
```

### PR DESCRIPTION
**Pull request by mvertes**
In a couple of occurences, tests with enabled race detector exposed
some concurrent accesses to the cancelation callback used in select and
channel operations send and recv for EvalWithContext. This change ensure
that all accesses to this object are protected by mutex.

Fixes #815.

### CODE REVIEW

File: interp/run.go [hunk 1]
```diff
@@ -94,9 +94,13 @@ func (interp *Interpreter) run(n *node, cf *frame) {
 		f = newFrame(cf, len(n.types), interp.runid())
 	}
 	interp.mutex.RLock()
-	f.done = reflect.SelectCase{Dir: reflect.SelectRecv, Chan: reflect.ValueOf(interp.done)}
+	c := reflect.ValueOf(interp.done)
 	interp.mutex.RUnlock()
 
+	f.mutex.RLock()
+	f.done = reflect.SelectCase{Dir: reflect.SelectRecv, Chan: c}
+	f.mutex.RUnlock()
```
Comment (mpl) [inline interp/run.go:102]: I'm probably missing the big picture (I need to look at the whole code), but just looking at this PR, it seems to me that we now have RLocks in all the places where we read from f.done, so it seems to be that here, we should have a Lock/Unlock, since we are writing to f.done.

Comment (mvertes) [reply interp/run.go]: Right. a Lock/Unlock is needed here.
