### PR TITLE
fix: add method checks for interface types

### LINKED ISSUE #452: interface type check false negative
The following program `sample.go` triggers an error:

```go
package main

type T struct{}

func (t *T) Error() string { return "T: error" }

var invalidT = &T{}

func main() {
    var err error
    if err != invalidT {
        println("ok")
    }   
}
```

Expected result:
```console
$ go run ./sample.go
ok
```

Got:
```console
$ yaegi ./sample.go
./sample.go:13:5: mismatched types .error and *main.T
```

### PR DESCRIPTION
**Pull request by mvertes**
Fixes #452

### CODE REVIEW

File: interp/type.go [hunk 1]
```diff
@@ -636,6 +636,47 @@ func (t *itype) finalize() (*itype, error) {
 	return t, err
 }
 
+// identical returns true if the given type is identical to the receiver one
+func (t *itype) identical(o *itype) bool {
```
Comment (ldez) [inline interp/type.go]: maybe you can use `equal` or `isEqual` instead of `identical`.

Comment (mvertes) [reply interp/type.go]: renamed `identical` to `equal`
